name: advent_of_code_2015
description: Advent of Code 2015 solutions
version: 1.0.0

environment:
  sdk: ">=2.17.5 <3.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies: { tuple: ^2.0.0 }
